"""Generated ambient briefs: CLAUDE.md / AGENTS.md at the worktree-ancestor directory.

.mgit/worktrees/<feature>/ is an ancestor of every worktree but outside every
git repo, so harnesses that walk parent directories for context files (Claude
Code reads CLAUDE.md; Codex, OpenCode and others read AGENTS.md) load the
feature's working memory automatically — zero install, zero git pollution.

These files are derived artifacts, regenerated after every FeatureManager
mutation and by 'mgit feature note/plan'. Never edit them by hand.
"""

from __future__ import annotations

import os
import tempfile

from mgit.core import memory
from mgit.core.workspace import Workspace
from mgit.models.types import FeatureInfo

BRIEF_FILES = ("CLAUDE.md", "AGENTS.md")

_HEADER = (
    "<!-- generated by mgit — do not edit; write via 'mgit feature note/plan', "
    "regenerate with 'mgit feature brief --refresh' -->\n\n"
)

_RITUAL = """
## Working here (mgit ritual for agents)

This directory holds one git worktree per repo for feature '{name}'. This file
is a snapshot from the last mgit operation — run `mgit feature brief` for live
state.

- Re-orient: `mgit feature brief` (memory + journal + live git facts, one call)
- Record decisions as you make them: `mgit feature note "..." --type decision`
- Keep the plan current: `mgit feature plan --status "..." --done N --add-next "..."`
- Commit across repos (auto-journaled): `mgit commit -m "..." -f .`
- Push feature branches / open PRs: `mgit push -f .` / `mgit feature publish`
- Full workspace state as JSON: `mgit context`

Commands run from inside this directory resolve to feature '{name}'
automatically, even if another session switches the workspace's active
feature. From outside it, pin the feature with `-f {name}` or
`export MGIT_FEATURE={name}` — never rely on the active pointer when
parallel sessions may be running.
"""


def render_feature_brief(ws: Workspace, feature: FeatureInfo) -> str:
    """Render the ambient brief: header + working-memory brief + learned skills + ritual."""
    from mgit.core import skill  # lazy: skill regenerates briefs, so avoid an import cycle

    data = memory.build_brief(ws, feature)
    parts = [_HEADER, memory.render_brief(data)]
    skills_block = skill.render_active_block(ws)
    if skills_block:
        parts.append("\n" + skills_block)
    parts.append(_RITUAL.format(name=feature.name))
    return "".join(parts)


def write_feature_brief(ws: Workspace, feature: FeatureInfo) -> None:
    """Atomically (re)generate the ambient brief files for a feature.

    Guarded: brief generation must never break the mutation that triggered
    it, so any failure is swallowed.
    """
    try:
        d = ws.worktrees_dir / feature.name
        d.mkdir(parents=True, exist_ok=True)
        text = render_feature_brief(ws, feature)
        for fname in BRIEF_FILES:
            fd, tmp = tempfile.mkstemp(dir=d, prefix=f".{fname}-")
            try:
                with os.fdopen(fd, "w", encoding="utf-8") as f:
                    f.write(text)
                os.replace(tmp, d / fname)
            except BaseException:
                try:
                    os.unlink(tmp)
                except OSError:
                    pass
                raise
    except Exception:
        pass
